# Base Image
FROM node:20.18.0-alpine3.19

WORKDIR /home/app/
RUN apk update && apk add nano

COPY package*.json .
RUN npm install


# Copying source code to docker image
COPY server.js server.js
COPY src src

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system -uid 1001 nodejs

USER nodejs

EXPOSE 3000
ENV PORT=8000

CMD [ "npm", "run", "dev" ]